language: python
script:
  - ./_travis/run.sh
before_install:
  - openssl version
after_success:
  - ./_travis/upload_coverage.sh
cache:
  directories:
  - ${HOME}/.cache
  - ${HOME}/.pyenv_cache
install:
  - ./_travis/install.sh
notifications:
  email: false
env:
  global:
    - GAE_SDK_PATH=${HOME}/.cache/google_appengine
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=flake8-py3
    - TOXENV=gae
    - TOXENV=docs
# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - language: generic
      os: osx
      env: TOXENV=py27 PYENV_VERSION=2.7.14
    - language: generic
      os: osx
      env: TOXENV=py34 PYENV_VERSION=3.4.9
    - language: generic
      os: osx
      env: TOXENV=py35 PYENV_VERSION=3.5.6
    - language: generic
      os: osx
      env: TOXENV=py36 PYENV_VERSION=3.6.7
    - language: generic
      os: osx
      env: TOXENV=py37 PYENV_VERSION=3.7.1
  allow_failures:
  - python: pypy-5.4
sudo: false
